[server]
host = "127.0.0.1"
port = 8088

[mysql]
hostname = "localhost"
config = "charset=utf8mb4&parseTime=True&loc=Local"
port = 13306
username = "root"
password = "123456"
database = "go_zzz_db"

[redis]
host = "127.0.0.1"
port = 6379
username = ""
password = ""

[zap]
level = "info"
prefix = "[golang] "
format = "console"
director = "logs"
encode-level = "LowercaseColorLevelEncoder"
stacktrace-key = "stacktrace"
show-LINE = true
log-in-console = true

[websocket]
biz = ["monitor", "chat"]